### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by christoph3r3w** [RobbyRisse/the-client-website#1]
More content can be added  to show all the functionalities of your website

**Comment by RobbyRisse** [comment]
can you elaborate a bit?

**Comment by christoph3r3w** [comment]
It is apparent that more functions still need to be added so that the user can interact more with the page. 
since most of the pages are not leading to any content yet. 

and by things to add I mean for example : 
* a page where someone can fill out a form to add their own event.
* more events as examples
![Screenshot 2023-12-20 000953](https://github.com/RobbyRisse/the-client-website/assets/144007933/28728166-9997-4ec5-8c4b-9b2d416e3a5e)
